https://www.datacamp.com/community/tutorials/markdown-in-jupyter-notebook

# Vid 1 ( Numpy Section Introduction )

##### Numpy (raw materials) - Matplotlib (visualize) - Scipy (statistics) - Pandas (read write manipulate)

<ul>

<li>Numpy => numpy array</li>
<li>Scalar 0D - Vector 1D -  Matrix 2D</li>
<li>dot product (inner product) => a.b = aT b</li>
<li>matrix multiplication C = AB</li>
<li>A (m,n) B (n,p) = C (m,p)</li>
<li>element wise dot product</li>
    
</ul>   

### Applications:

<ol>
<li>Linear regression</li>
<li>Logistic regression</li>
<li>Deep neural network</li>
<li>K-maens clustering</li>
<li>Density Estimation</li>
<li>Principal Component Analysis</li>
<li>Matrix Factorization ( Recommender systems )</li>
<li>SVM</li>
<li>Markov models, Hidden markov models</li>
<li>Control systems</li>
<li>Game Theory</li>
<li>Operations research</li>
<li>Portfolio optimization</li>    

</ol>

# Vid 2 ( Arrays vs. Lists )

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

A = np.array(L)
#or
# A = np.array([1,2,3])

In [3]:
for e in L:
    print(e)
#     print(type(e))
    
# print(type(L))

1
2
3


In [4]:
for e in A:
    print(e)
#     print(type(e))
    
# print(type(A))

1
2
3


In [5]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [6]:
# numpy array has not append ( has fixed size ) because of memory efficiency
# A.append(4)

In [7]:
# concat two lists
print(L + [5])

# broadcasting
print(A + np.array([4]))

# print(A + np.array([5,6,7]))
# print(A + np.array([5,6]))

[1, 2, 3, 4, 5]
[5 6 7]


In [8]:
print(2 * A)
print(2 * L)
# print(2 + L)
print(L + L)

[2 4 6]
[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [9]:
L2 = []
for e in L:
    L2.append(e + 3)
    
print(L2)

[4, 5, 6, 7]


In [10]:
L2 = [e+3 for e in L]
print(L2)

print(A+3)

[4, 5, 6, 7]
[4 5 6]


In [11]:
L2 = [e**2 for e in L]
print(L2)

print(A**2)
print((A**2)[1])

[1, 4, 9, 16]
[1 4 9]
4


In [12]:
print(np.power(A,2))
print(np.sqrt(A))
print(np.log(A))
print(np.exp(A))
print(np.tanh(A))

[1 4 9]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.76159416 0.96402758 0.99505475]


# Vid 3 ( Dot products )

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [13]:
a = np.array([1,2])
b = np.array([3,4])

In [14]:
dot = 0
for e,f in zip(a ,b):
    dot+=e*f
    
print(dot)

11


In [15]:
dot = 0
for i in range(len(a)):
    dot+=a[i]*b[i]
    
print(dot)

11


In [16]:
print(a*b)

print(np.dot(a,b))
print(a.dot(b))
print(a@b)

print(np.sum(a*b))
print((a*b).sum())

[3 8]
11
11
11
11
11


$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [17]:
amag = np.sqrt(a.dot(a))
print(amag)

print(np.linalg.norm(a))

2.23606797749979
2.23606797749979


In [18]:
cosanlge = a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))
print(cosanlge)

0.9838699100999074


In [19]:
angle = np.arccos(cosanlge)
#radians
print(angle)


#degree
print(np.rad2deg(angle))

0.17985349979247847
10.304846468766044


# Vid 4 ( Speed test )

In [22]:
import time

def execution_time_calculator(start_time):
#     print("--- %s seconds ---" % (time.time() - start_time))
    return time.time() - start_time

In [23]:
a = np.random.randn(100)
b = np.random.randn(100)

T = 100000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += a*b
    return result

t0 = time.time()
for t in range(T):
    slow_dot_product(a, b)
dt1 = execution_time_calculator(t0)

t0 = time.time()
for t in range(T):
    a.dot(b)
dt2 = execution_time_calculator(t0)

print("dt1/dt2: ", dt1/dt2)

dt1/dt2:  228.11385828686045


In [24]:
time.time()

1614337735.9090571

# Vid 5 ( Matrices )

In [27]:
L = [[1,2],[3,4]]
print(L)
print(L[0][1])

[[1, 2], [3, 4]]
2


In [31]:
A = np.array(L)
print(A)
print(A[0][1])
print(A[0,1])

[[1 2]
 [3 4]]
2
2


In [35]:
print(A[:,0])
print(A[:,1])
print(A[0,:])

[1 3]
[2 4]
[1 2]


In [41]:
# transpose
print(A.T)
print(np.exp(A))
print(np.exp(L))


[[1 3]
 [2 4]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [47]:
B = np.array([[1,2,3],[4,5,6]])
# print(B)
print(A.dot(B))
# print(A.dot(B.T))

[[ 9 12 15]
 [19 26 33]]


In [57]:
print(np.linalg.det(A))
print(np.linalg.inv(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [60]:
print(np.linalg.inv(A).dot(A))
print(A.dot(np.linalg.inv(A)))
# identity matrix A A.T = I
# 0.0000000000004 and e^-16 is because of not being exact

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [66]:
print(np.trace(A))
print(np.trace(B))

print(np.diag(A))
print(np.diag(B))

#diag for vector
# diag => matrix ==> vector  & vector ==> matrix
print(np.diag([1,2,3,4]))

5
6
[1 4]
[1 5]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [90]:
print(np.linalg.eig(A))
Lam ,V = np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [91]:
print(V[:,0] * Lam[0])
print(A @ V[:,0])
# x , y prints both
# V[:,0] * Lam[0] , A @ V[:,0]
# V[:,0] * Lam[0] == A @ V[:,0] is element wise

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]


In [114]:
print(np.allclose(V[:,0] * Lam[0] , A @ V[:,0]))
print(np.allclose(V @ np.diag(Lam), A @ V))

False
False


In [115]:
# np.linalg.eigh for complex numbers

# Vid 6 ( Solving linear systems )

#### Solving with inverse is slow... use np.linalg.solve

In [116]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

In [117]:
np.linalg.solve(A,b)

array([1500.,  700.])

In [118]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# Vid 7 ( Generting Data )

In [119]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [120]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [121]:
print(10*np.ones((2,3)))

[[10. 10. 10.]
 [10. 10. 10.]]


In [123]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [124]:
print(np.random.random())

0.2411841425119341


In [133]:
# (0,1)
print(np.random.random((2,3)))

# (-1,1)
print(np.random.randn(2,3))

[[0.68680729 0.01236846 0.57562069]
 [0.61215159 0.40438725 0.89663027]]
[[ 0.91263294 -0.55609634  0.94687152]
 [ 0.75635558 -0.22797173 -0.27318345]]


In [135]:
R = np.random.randn(1000)

In [144]:
print(R.mean())
print(np.mean(R))

# print(R.sum())
print(R.var())
print(R.std()) # var^2

0.01080824338020038
0.01080824338020038
1.003279988660848
1.0016386517406606


In [164]:
R = np.random.randn(10000, 3)
print(R.shape)

(10000, 3)


In [165]:
print(R.mean(axis=0))
print(R.mean(axis=1))

[ 0.00706345 -0.00950693  0.00037   ]
[-0.10302349 -0.12152537 -0.76051302 ...  0.81470274  0.28134267
 -0.52288139]


In [166]:
print(np.cov(R))
print(np.cov(R).shape)

[[ 0.10564069 -0.21556948  0.04394519 ...  0.1931064  -0.28753384
   0.17516573]
 [-0.21556948  0.4420442  -0.09117645 ... -0.34301457  0.60594892
  -0.36049996]
 [ 0.04394519 -0.09117645  0.01932791 ...  0.04475124 -0.13300198
   0.07499871]
 ...
 [ 0.1931064  -0.34301457  0.04475124 ...  1.56169963 -0.07064856
   0.24776534]
 [-0.28753384  0.60594892 -0.13300198 ... -0.07064856  0.95385254
  -0.50402979]
 [ 0.17516573 -0.36049996  0.07499871 ...  0.24776534 -0.50402979
   0.29478733]]
(10000, 10000)


In [170]:
# cov standard is column for each observation so transpose it to make it ok
print(np.cov(R.T))
print(np.cov(R.T).shape)

# or 
print(np.cov(R,rowvar=False))

[[ 0.9981379  -0.01231072  0.01698709]
 [-0.01231072  1.02213234  0.01180985]
 [ 0.01698709  0.01180985  1.01381472]]
(3, 3)
[[ 0.9981379  -0.01231072  0.01698709]
 [-0.01231072  1.02213234  0.01180985]
 [ 0.01698709  0.01180985  1.01381472]]


In [184]:
print(np.random.randint(0,10,(2,3)))
print(np.random.choice(7))

[[8 9 0]
 [7 9 5]]
2


In [188]:
print(np.random.choice([1,2,3,4,5,6]))
print(np.random.choice([1,2,3,4,5,6],5))
print(np.random.choice([1,2,3,4,5,6],(3,3)))

5
[6 4 6 5 4]
[[1 2 3]
 [6 2 6]
 [3 3 3]]


# Vid 8 ( Numpy Exercise )

In [227]:
a = np.random.random((3,3))
b = np.random.random((3,3))

T = 1000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += a*b
    return result

def slow_matrix_multiplication(a, b):
    result = [ [0 for i in range(b.shape[1])] for j in range(a.shape[0])]
#     result = np.zeros((a.shape[0],b.shape[1]))

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            result[i][j] = slow_dot_product(a[i:], b[:,j])

    return result

t0 = time.time()
for t in range(T):
    slow_matrix_multiplication(a, b)
dt1 = execution_time_calculator(t0)


t0 = time.time()
for t in range(T):
    a.dot(b)
dt2 = execution_time_calculator(t0)

print("dt1/dt2: ", dt1/dt2)

dt1/dt2:  99.00560658475486


# Vid 9 ( Where to learn more numpy )

#### step 1: learn ML algorithms